収支管理　一応完成
2023AIT-OOP2-G06/income-and-expenditure-app pull request #18
Opened 2024-01-25 04:58 UTC by ASRockI

## 課題
- https://github.com/https://github.com/2023AIT-OOP2-G06/income-and-expenditure-app/issues/18

## 概要

このセクションでは、このPRの目的と概要を簡潔に説明してください。
収支管理機能が完成したため、mergeのため。
また、何か仕様の不足がある場合の指摘をお願いしたい。

## 変更点

このセクションでは、具体的な変更点や修正箇所を箇条書きでリストアップしてください。
1.画面に収支表示機能を追加
2.月を変えるボタンの機能実装
3.デザインの調整

## 影響範囲

このセクションでは、このPRが影響を及ぼす範囲や他の機能への影響を説明してください。

incomeAndOutgoディレクトリ以下のimgディレクトリ、ShiftMain.js以外の全て

## チェックリスト

- [v]  コンパイルできるか？

## その他コメント

2024-01-25 05:33 UTC, harutiro requested changes
コメントしました。
収支のグラフがアニメーションでしっかりと動いていてとてもすごいです！！
一人でここまで実装されていてびっくりしました。

編集して欲しくない部分が、一部編集されてしまっているので修正をお願いします。
また、バグが少々ありそうなので、そこも修正お願いします。

エラーでわからないところがあれば一緒に修正しましょう

2024-01-25 05:33 UTC, harutiro commented on .vscode/settings.json
このファイルは打ち上げないようにしてください。

2024-01-25 05:33 UTC, harutiro commented on .DS_Store
このファイルは打ち上げないようにしてください

2024-01-25 05:33 UTC, harutiro commented on docs/core/scss/styles.css
このファイルは編集しないでください。

2024-01-25 05:33 UTC, harutiro commented on docs/core/scss/styles.css.map
このファイルは編集しないでください

2024-01-25 05:33 UTC, harutiro commented on docs/features/incomeAndOutgo/js/incomeAndOutgoMain.js
収支の部分で、働いた金額 残った金額がうまく動いていなさそうです。

2024-01-25 06:08 UTC, ASRockI commented on docs/features/incomeAndOutgo/js/incomeAndOutgoMain.js
直せたか確認お願いします。

2024-01-29 17:18 UTC, harutiro approved these changes
LGTM OKです

2024-01-29 17:19 UTC, merged