Outgo(支出管理機能)の完成
2023AIT-OOP2-G06/income-and-expenditure-app pull request #2
Opened 2024-01-19 03:18 UTC by k22133

## 課題
- https://github.com/https://github.com/2023AIT-OOP2-G06/income-and-expenditure-app/pull/2

## 概要

支出管理機能が完成したため、mergeのためのPR。
同時に、何か仕様の不足がある場合の指摘の機会。

## 変更点

- 画面に支出入力機能を追加
- 各ボタンの機能実装
- デザインの微調整

## 影響範囲

Outgoディレクトリ以下、imgディレクトリ以外の全て

## チェックリスト

- [v]  コンパイルできるか？

## その他コメント
このMDの課題の所、何をすれば良いか分からない。
適当に直しはしたが、合っているか不明。

2024-01-19 08:44 UTC, harutiro requested changes
PRありがとうございます！！
JSやHTML、CSSが初めての状態で、本当に素晴らしい機能ができたと思います。
1週間でここまで実装できてすごいです。

ですが、少々動作の問題と、デザインの問題を指摘しました。
対応のほどよろしくお願いします。

2024-01-19 08:44 UTC, harutiro commented on docs/features/outgo/js/OutgoMain.js
> +        // 今日の日付を取得
今の所、ボタンを押しても、ただリストが見えなくなってしまう謎の機能になっているので、このボタンをそのまま使っていきたい場合は、どの年のどの月だけをみていきたいのかを記述するといいかなと思いました。
<img width="439" alt="スクリーンショット 2024-01-19 17 14 25" src="https://github.com/2023AIT-OOP2-G06/income-and-expenditure-app/assets/74090756/5657d204-c18f-4667-8b65-9850e8011b32">

2024-01-19 08:44 UTC, harutiro commented on docs/features/outgo/outgoScreen.html
支出を確認というButtonが実装されてる48行目の部分なのですが、基本的にはユーザーはボタンを押して更新をすることはないので、Button自体は消しても大丈夫だと思います。

2024-01-19 08:44 UTC, harutiro commented on docs/features/outgo/js/OutgoMain.js
>          console.log(outgo);
現状順番が、古い順になっています。
新しく追加した時に、リストが多くなってくると画面に変更が見られる、少々ユーザー体験がよろしくないです。
DBについて、長尾くんにまた更新をしてもらい、順番を自由に入れ替えれるようにしたいと思いますので、ここが変更されるかもと思ってもらえると助かります。

2024-01-19 08:44 UTC, harutiro commented on docs/features/outgo/js/OutgoMain.js
> +            alert(e.message);
ここで、エラー処理を行って、throwでどのように処理するかをまとめるところは、本当にすごいです。
綺麗なコードが作れていると思います。

2024-01-19 08:44 UTC, harutiro commented on docs/features/outgo/outgoScreen.html
>                  const outgoMain = new OutgoMain();
この部分なのですが、今のままだとデフォルトのHTMLのフォームになっていて少々無機質で寂しいです。
ですのでBootstrapを用いて少しデザインを整えてもらえるといいとおもいます。

この辺りの公式ドキュメントを読んでもらえればやり方がまとまっています。
https://getbootstrap.jp/docs/5.3/forms/overview/

bootstrap自体のやり方がわからない場合は下記URLの動画を参照してください
[https://www.youtube.com/watch?v=kcPBAysgPPg&ab_channel=徳田啓【プログラミング学習チャンネル】](https://www.youtube.com/watch?v=kcPBAysgPPg&ab_channel=%E5%BE%B3%E7%94%B0%E5%95%93%E3%80%90%E3%83%97%E3%83%AD%E3%82%B0%E3%83%A9%E3%83%9F%E3%83%B3%E3%82%B0%E5%AD%A6%E7%BF%92%E3%83%81%E3%83%A3%E3%83%B3%E3%83%8D%E3%83%AB%E3%80%91)

# 該当の部分
<img width="434" alt="スクリーンショット 2024-01-19 17 30 51" src="https://github.com/2023AIT-OOP2-G06/income-and-expenditure-app/assets/74090756/90eabc5c-8369-45f3-b810-2332aba88e9d">

# 目指して欲しいデザイン。
<img width="569" alt="スクリーンショット 2024-01-19 17 31 30" src="https://github.com/2023AIT-OOP2-G06/income-and-expenditure-app/assets/74090756/ba6ba587-fcbb-4037-84a8-ee78c3ca379a">

2024-01-20 10:59 UTC, k22133 commented
「Conversation」と書いてある程だから、「このやりとりはGitHub上でできる」というのはここのこと？

コードを見てみたけど、issue「データを保存することができるか？」というのはoutgoRepository.setOutgo(outgo);で既にできてそうなものだけどどう？バリデーションチェックの件もconsole.log(outgoList);で既にできてそうだけど。
DBが分からないから、コード上では問題なさそうでも本当にできているのか判断がつかない。

デザインissueの方の、「画面が崩れていないか」に関して、スマホ版はどうやって確認できる？スマホでURLを検索にかけてもアクセスできないし、ネットで調べてもソースを見たいという旨のものしかヒットしない。

変更をコミットしたらこのPRに反映した感じがするけど、変更版は確認できる？デザインが変わっていると思うから、改めて判断してほしい。

2024-01-20 12:29 UTC, harutiro commented
> 「Conversation」と書いてある程だから、「このやりとりはGitHub上でできる」というのはここのこと？
そうですそうです、ここのことです。

もしコードに関することで、話し合いたいことがあれば、ここのReplayというところで、話し合うこともできるから、そちらも使ってみてね。
<img width="869" alt="スクリーンショット 2024-01-20 21 24 03" src="https://github.com/2023AIT-OOP2-G06/income-and-expenditure-app/assets/74090756/c0541764-76df-48d7-98e8-d73919656bbc">


> コードを見てみたけど、issue「データを保存することができるか？」というのはoutgoRepository.setOutgo(outgo);で既にできてそうなものだけどどう？バリデーションチェックの件もconsole.log(outgoList);で既にできてそうだけど。
DBが分からないから、コード上では問題なさそうでも本当にできているのか判断がつかない。

保存ができているかどうか？というのは、Console.log()などでチェックをしたり、実際に保存をしたデータが画面のリストに表示されれば今回は大丈夫。
実際に自分が確認してみたけど、しっかり保存ができているので大丈夫です。

> デザインissueの方の、「画面が崩れていないか」に関して、スマホ版はどうやって確認できる？スマホでURLを検索にかけてもアクセスできないし、ネットで調べてもソースを見たいという旨のものしかヒットしない。

fn + F12を押すことで、開発者ツールを開くことができます。
そこで、これって書いてある場所を変えることで、スマホサイズにしたり、タブレットサイズにすることもできます。

<img width="1680" alt="スクリーンショット 2024-01-20 21 26 51" src="https://github.com/2023AIT-OOP2-G06/income-and-expenditure-app/assets/74090756/057ae125-55d3-450f-b532-0c85052e4570">

詳しくは下記URLを参考にしてみてください。
https://www.site-convert.com/archives/1507#outline__1_4

> 変更をコミットしたらこのPRに反映した感じがするけど、変更版は確認できる？デザインが変わっていると思うから、改めて判断してほしい。

ここに、最終コミットが書いてあるから、変更がされていそう！！
大丈夫です。
<img width="955" alt="スクリーンショット 2024-01-20 21 29 19" src="https://github.com/2023AIT-OOP2-G06/income-and-expenditure-app/assets/74090756/67d2de44-e219-4c0b-9258-2b1f5d846969">

2024-01-20 12:34 UTC, harutiro approved these changes
LGTM
OKです

2024-01-20 12:34 UTC, merged